Happynyamy/Happiggy-bank-iOS

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Model/Bottle.swift, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
유리병 리스트 UI 구성 (issue #14)
- 유리병 리스트 뷰 컨트롤러
- 리유저블셀을 사용해 테이블 뷰 구성
- 리스트가 비어있을때와 차있을 때 내비게이션 타이틀 변경 및 테이블 뷰 라벨 visible/hidden
- 유리병 테이블 뷰 셀
- 추후 이미지로 배경 교체 예정
- UI 상세(이미지 등)
- 데이터 바인딩
- 각 유리병 선택시 HomeVC에 반영
=> [feat] 유리병 리스트 UI 구성 #14

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 이슈 #17
<br>
- 로컬에서 brew 로 SwiftLint 설치 후 CLI 에서는 작동하는데 Xcode 에서는 계속 설치되지 않았다고 떠서 Build Phase 의 Run Script 를 변경(경로 관련 문제)
- 바뀐 런스크립트가 은빈님 로컬에서도 괜찮은지 확인 필요
- 커밋 메시지 분류가 애매한 것 같아서 chore 항목 추가
- [참고 링크](https://doublesprogramming.tistory.com/256)
=> [chore] SwiftLint 경로 문제로 build phase run script 변경 #17

Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Happiggy-bank/Happiggy-bank/Info.plist, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
issue #21 
- Storyboard 추가 후 TabBarController로 각 화면 연결
- 각 탭에 NavigationController 추가 (Settings에는 필요 없을 수도 있음)
- HomeViewController에 이제 사용되지 않는 UI요소 및 메서드 삭제
- 기존 HomeVC에서 하던 '초기 이미지 구성'을 BottleVC로 이동
- 진행중인 유리병이 없을 때 BottleVC의 imageView에서 유리병 추가 이미지 띄우고 onTapGesture 추가 
- UI디자인 완료시 BottleVC 레이아웃 변경 및 HomeView에 유리병 라벨 추가
- Tab간 스와이프 이동(-> 논의 후 추가)
=> [feat] 화면 재구성 #21

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Happiggy-bank/Happiggy-bank/AppDelegate.swift, Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/Extensions/NSManagedObject+EntityName.swift, Happiggy-bank/Happiggy-bank/Happiggy-bank.xcdatamodeld/Happigy-bank.xcdatamodel/contents, Happiggy-bank/Happiggy-bank/Model/Bottle.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
- 이슈 #20 
- 코어데이터 저장, 호출을 담당하는 인스턴스 생성
- 싱글턴으로 앱 전체에서 하나의 persistence container 공유 
- 호출, 저장, 삭제를 위한 메서드 추가
-  삭제는 작업 편의를 위해 생성했고 추후 삭제 예정
<br>
- 저금통-쪽지 관계 1:N 으로 설정, 저금통 삭제 시 쪽지도 함께 삭제되도록 함
- 불리언 프로퍼티들은 디폴트 값 다 false 로 주고 논옵셔널하게 만듦
<br>
- 객체 생성 시 편의를 위한 convenience init 추가 (저장은 별도) 
- 편의를 위해 옵셔널한 프로퍼티들 연산 프로퍼티로 닐 코알리싱
- 값이 수정될 수 있는 불리언들, 저금통 제목 외에는 다 get-only
<br>
- 범용성 있는 fetchRequest 를 만들어주는 메서드와 열린/닫힌 저금통에 대한 fetchRequest 를 생성하는 메서드 추가
- 각각 저금통 리스트, 홈뷰에서 사용할 수 있도록
<br>
- 에러 처리 관련 작업
- 코어데이터의 _ 붙은 프로퍼티들 private 하게 만들어버리기?
- 저금통 진행 정도 같은 프로퍼티를 Bottle Class 안에 선언할까 고민하다가 작업이 너무 늦어지는 것 같아 일단 패스했습니당
- 제가 호출, 저장, 삭제 다 잘 되는지 확인하긴 했는데 혹시 문제 있을 수도 있으니까 문제 생기면 바로 알려주세요...!
=> [feat] 코어데이터 작업 #20

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Extensions/CATransition+PopupAnimation.swift, Happiggy-bank/Happiggy-bank/Extensions/UIViewController+FadeOut.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteColorPickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNotePopupViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
이슈 #26 
- NewNoteDatePickerViewController, NewNoteColorPickerViewController, NewNoteTextViewController
- 새로운 뷰컨트롤러를 present modally + (over)fullScreen 옵션으로 적용해서 사용
- 내장된 cross dissolve 애니메이션 효과 사용 위함
- navigation bar 추가 해서 취소/이동/저장 버튼 이동 효과만 구현 해둠
- 투명 배경 + 하단선 제거를 위해 각 뷰컨의 viewDidLoad 에 로직 추가 
<br>
- buttonDidTap 분기 실수 수정(이미 모든날 쪽지 작성한 경우 <-> 쪽지 작성 가능한 경우)
- 쪽지 작성 가능한 경우 데이트 피커 뷰를 띄우도록 함
- 쪽지 작성 뷰 컨트롤러에서 돌아올 수 있도록 unwindCallDidArrive(segue:) 메서드 추가
<br>
- NewNotePopupController 의 메서드였던 fadeOut() 을 화면 전환에 쓰려고 옮겨옴
<br> 
- Constant 파일 최대 줄 길이 넘었다고 SwiftLint 경고 뜨는 거 짱받아서 해당 파일만 줄 수 disable 설정
- Constant 에 SegueIdentifier enum 추가
- 기존의 NewNotePopupController 는 이슈 #26 완료하면 삭제하겠습니다(거기서 소스 뜯어다가 쓰고 있어서...ㅋㅋㅋㅋㅋ)
<br>
- 날짜 피커, 컬러 피커, 쪽지 작성 뷰 순차적으로 작업 예정
<br>
여기까지만도 너무 오래걸려서 다 하고 올리면 너무 큰 풀리퀘가 될 거 …
=> [feat] 쪽지 추가를 위한 뷰 컨트롤러들 생성 및 연결 #26

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
- 이슈 #32 
<br>
- 새로운 쪽지 컬러 피커에서 unwind segue 추가하면서 저금통 피커의 unwind segue 를 삭제했던 게 원인
- 스토리보드에서 segue 다시 설정
흑흑 실수로 어제 컬러 피커에서 unwind segue 추가하면서 스토리보드에서 잘못 건드렸나봐요 죄송합니다...바꿔서 빠르게 머지했습니다...!
=> [fix] 새로운 저금통 기간 피커에서 저장 버튼 누르면 충돌 발생하는 문제 수정 #32

Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib, Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift
- 이슈 #50 
<br>
UI 디자인 반영하면서 좌우 패딩을 변경했는데, 변경 전에는 디바이스에서 잘 작동했고, 변경 후에도 다른 시뮬레이터에서는 잘 작동했는데 아이폰 13미니 디바이스와 시뮬레이터 모두에서 스크롤 하면 이미지 위치가 틀어지면서 애니메이션에도 버그가 발생하는 문제가 있었습니다
은빈님 코드 참고해서 noteImageView leading, trailing anchor 를 contentView 와 같게 하고 layoutSubviews 에서 contentView 의 프레임을 조정하는 방식으로 변경했는데 혹시 이렇게 하면 왜 해결되는 건지 함 봐주실 수 있을까용(원래는 걍 xib 파일에서 noteImageView 의 constraint 들을 contentView 에 패딩값만큼 더하거나 빼서 설정하는 방식이었습니다)
=> [fix] 쪽지 리스트에서 셀 내부 뷰들의 크기 및 애니메이션 버그 수정 #50

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/CGSize+Area.swift, Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/Grid.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
- 이슈 #43
- 이슈 #36 
<br>
- 쪽지 이미지들을 작성 순서대로 유리병 안에 나타내기 위해 그리드 추가
- UIDynamics 쓰면 CPU 폭발해서 차선책 
- 그리드를 사용해서 유리병 내부 영역을 n개의 CGRect 로 나눈 다음, 이를 좌표로 사용해 해당 위치에 subview 를 추가하는 방식
- gridContainer 가 실체가 있는 UIView 고, grid 는 내부의 투명 뼈대같은...그런...
- 쪽지 이미지들은 grid 가 아니라 gridContainer 에 추가됨
- **문제...스크롤 진짜 빠르게 하면 CPU 90%까지 치솟음 흑흑**
- bottle cell height 수정 (vertical spacing 대신 horizontal padding 이 적용되고 있었음)
- 라벨에 디자인 색상 적용, 날짜 라벨 2022.03.01 -> 2022 03.01 형태(연도와 달 사이 점 제거)로 변경 
- 셀 재사용 시 grid, noteView 를 매번 리셋해줘야 해서 관련 함수도 추가
<br>
- 그리드 좀 더 섬세하게 분할 (쌓인 모습 예쁘게...)
- 기간 별 사이즈 재확인 필요
=> [feat] 저금통 리스트 셀에 쪽지 이미지들을 담은 그리드 추가, 셀 라벨 색상 적용 #43 #36

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Subview/NoteView.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/Grid.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleViewModel.swift
- 이슈 #65 
<br>
- 그리드 추가, 각 쪽지 위치를 지정해서 위에서 떨어지는 게 아니라 해당 위치에 쪽지가 떨어지도록 함 
- 그리드로 위치 잡아준 다음에 중력 효과  
- 잔떨림 현상 많이 줄어들은 것 확인!
- bottleNoteView 쪽으로 코드를 아예 빼고 싶었는데 무한의 세그폴트가 나서...나중에 리팩토링 해보겠습니다.. 
<br>
- 제가 첨에 화면이 원하는대로 안나와서(지금 보니까 아래 수정했다는 그리드 조건 때문이었던 것 같음...) 전체적으로 이번 파트 관련해서constraint 를 좀 손 댔는데 혹시 보시고 이건 건드리면 안됐다 하는 거 있으시면 제가 바로 원상복귀 해두겠습니당
<br>
- 가운데 정렬을 위해 grid 영역 분할 조건 변경
<br>
- 유저가 새 쪽지를 추가했을 때 홈뷰로부터 알림 받아야 함
- 해당 용도로 contextDidChange 메서드를 구현해놨고, 그리드에 뷰 추가 해놨는데 나중에 떨어지는 위치 수정해야 될것 같고 제가 더 이상 머리가 돌아가지 않아서 새 쪽지를 dynamic item 으로 추가하는 건 못했습니다... 
<br>
**은빈님이 설정해주신 베지에 패스랑 중력 영역이 고통받던 제게 매우 큰 힘이 되었습니다 다시 한번 감사의 말씀....**
=> [feat] 홈 화면 저금통 뷰 그리드 추가 #65

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteGreen.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePink.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePurple.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteWhite.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteYellow.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Button/CapsuleButton.swift, Happiggy-bank/Happiggy-bank/Extensions/UILabel+ParagraphStyle.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/CapsuleButton.xib, Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
- 이슈 #54 
- 이슈 #55 
- 이슈 #58 
- 이슈 #35 
<br>
- 전체 개봉 버튼을 누르면 알림을 띄워서 다시 한 번 확인하도록 함
- 전체 개봉 시 현재 보이는 쪽지는 애니메이션과 함께 개봉되고 나머지는 바로 효과 없이 개봉되도록 처리 + 개봉 후 버튼 숨김
- 처음에는 전부 reloadRows 로 했으나 로딩이 오래걸리는 문제가 있어 보이는 쪽지만 reloadRows 로 바꿈
- 라벨 행간, 자간 조정
- extension으로 빼둬서 쓸 일 있으시면 바로 쓰시면 됩니당!
<br>
=> [feat] 쪽지리스트 전체 개봉 버튼, 쪽지 개수 라벨 구현, 쪽지 내용 라벨 행간 및 자간 조정 #54 #55 #58 #35

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Subview/TagCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/TagViewFlowLayout.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
- 이슈 #73 
- 이슈 #72 
<br>
- 태그들의 모음과 같은 가운데 정렬한 컬렉션 뷰로 변경
- flowlayout 사용
- 코어데이터 관리를 위해 FetchedResultController 도입
- 저금통 리스트에서 이제 단순히 저금통만 넘겨받으면 됨
-  아직 저희가 이동, 삭제 이런 기능은 넣지 않는 것 같아서 델리게이트 메서드들은 구현하지 않았습니다
- 저금통 리스트에 뷰모델에 있는 거 슥 옮겨가셔서 조금씩만 수정하시면 될 거 같고, 아님 일단 딴 거 부터 하시고 막바지에 가서 제가 옮겨도 될 것 같아요..!
<br>
- UI 디자인 반영
- 디테일뷰와 연결
- 애니메이션 효과...? 뭐가 좋을까요.. . 
- 삭제 기능은 일단 당장 급한 게 아니라고 생각해서 생략했습니다
=> [feat] 쪽지 리스트 컬렉션 뷰로 변경, fetched result controller 적용 #72 #73

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Subview/NoteView.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/Gravity.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
- 이슈 #82 
<br>
- 디자인 변경에 따라 홈뷰에서 저금통 영역을 화면 전체를 차지하도록 재설정
- 저금통 뷰 그리드 범위도 쪽지가 자연스럽게 펼쳐지는 범위에서 최대로 지정
- 중력 영역 설정을 뷰 바운드를 그대로 사용하기 위해 바운더리 설정 방식 변경
- 쪽지 이미지가 겹치는 정도를 줄이고, 테트리스 모양 아니고 자연스럽게 쌓이도록 collision path type 을 ellipse (원형)으로 변경
- cpu 사용량을 줄이기 위해서 뷰가 나타날때 gravity 를 적용하고, 사라질 때는 멈춤
<br>
- 중력 정도 조정
- 쪽지 이미지 해상도 변경 필요
=> [feat] 저금통 뷰 영역, 중력 범위, 쪽지 뷰 충돌 범위 재설정 

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/UIView+ZoomAnimation.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib, Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift, Happiggy-bank/Happiggy-bank/Subview/TagCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/UPCarouselFlowLayout.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteDetailViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteDetailViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
- 이슈 #90 
<br>
- 쪽지 리스트에서 스크롤바 위치 조정을 위해 컬렉션 뷰에 넣었던 마진을 없애고 섹션 인셋을 설정하는 방식으로 전환했습니다
- 쪽지 리스트 스크롤 시, 그리고 셀 선택 시 애니메이션을 추가했습니다
- 사실 셀 선택 애니메이션이 메인이고 리스트 스크롤은 걍 하는 김에 해본거라 보시고 조잡하다 싶으시면 편하게 알려주세요 머지 전에 삭제하겠습니당
- 쪽지 리스트에서 특정 셀 선택 시 해당 셀의 내용을 담은 쪽지 셀이 중앙에 뜨는 캐러셀 뷰를 구현했습니다.  
-  https://github.com/zepojo/UPCarouselFlowLayout 를 바탕으로 불필요한 코드를 제거하고 변수 네이밍 등을 수정했습니다. 
- 일단 지쳐서 지금은 못했는데 캐러셀에서 페이지 넘길 때 햅틱 반응을 추가할까 하는데 혹시 어떠신가용
<br>
- 쪽지 디테일 뷰 디자인 피스 되면 해당 사항 반영
=> [feat] 쪽지 디테일 캐러셀 뷰 구현

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
- 이슈 #96 
<br>
- 보틀뷰 컨트롤러의 역할을 UI다이내믹스 를 사용해 쪽지 노드들을 추가/관리하는 것으로 축소했습니다. 
- 저금통 상태에 따른 배경화면 설정, 유저 탭 인식, 저금통 추가/개봉, 쪽지 추가 뷰들을 띄우는 작업은 모두 홈뷰컨트롤러로 이동했습니다. 
- 이에 따라 기존에 보틀뷰컨트롤러 에서/로 perform/rewind 되던 segue 를 홈뷰컨트롤러와 연결해줬습니다
- 저금통 추가 네임필드 segue 는 변경했으나 날짜피커의 경우 이제 홈뷰로 돌아오는 게 아니고 메세지뷰가 추가될 예정이라 불필요한 것 같아 unwind segue 를 삭제만 하고 다시 연결은 하지 않았습니다...!
- 관련해서 스토리보드도 위치를 전체적으로 수정했습니다...!
=> [feat] 홈뷰컨트롤러, 보틀뷰컨트롤러 리팩토링 #96

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
- 이슈 #95 
<br>
- 뷰 하단의 팀 라벨을 누르면 메일을 보낼 수 있는 경우에만 메일 작성창이 모달로 뜨게 했습니다. 
- 제목은 [행복저금통] 이 자동으로 들어가도록 했고, 
- 내용에도 간단한 안내(e.g. 버그 발생 시 디바이스 이름, iOS 버전을 함께 알려주시면 감사하겠습니다)를 쓸 수는 있는데 일단은 공백으로 뒀습니당 
- 다른 풀리퀘에 코드가 있어서, 추후에 작성창을 띄울때 햅틱을 추가할 예정입니다.
- 메일을 보낼 수 없는 경우에는 굳이 알림을 띄울 필요가 없다고 생각해서 아무것도 하지 않게 했습니다. 
- 유저가 메일 창에서 작업을 하고 다시 앱으로 돌아왔을 때 상태에 따라 알림을 띄울 수 있는데(전송, 저장,에러 등) 알림을 띄울 사안인가 싶어서 일단 그냥 뒀고, 관련해서 의견 주시면 감사하겠습니다!
<br>
- (논의 후 필요하면) 결과 처리, 햅틱 추가
=> [feat] 개발자에게 메일 보내기 구현 #95

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Happiggy-bank/Happiggy-bank/AppDelegate.swift, Happiggy-bank/Happiggy-bank/Storyboard/SettingsToggleButtonCell.xib, Happiggy-bank/Happiggy-bank/Subview/SettingsToggleButtonCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/NotificationSettingViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NotificationSettingViewModel.swift
issue #91 
- SettingsToggleButtonCell의 스위치 삭제
- NotificationSettingViewController 추가 및 스위치 관련 기능 추가
- 스위치 삭제 및 변경된 디자인에 따라 아이콘 뷰 추가
- 버전 셀에도 적용하려고 했는데 버전 셀 구조 자체가 바뀌는 것 같아서 일단 안 건드렸습니다.
- SettingsToggleButtonCell에 뷰 컨트롤러 추가
- 노티피케이션 관련 로직 추가
- 처음 스위치 눌렀을 때 -> 요청
- granted : 스위치 on, 현재 진행중인 저금통 종료 기간에 따라 14일간 노티피케이션 스케줄링
- disabled: 스위치 off
- 이후 스위치 눌렀을 때
- granted
- on: 위와 동일
- off: 스케줄링된 모든 노티피케이션 삭제 
- disabled: 스위치 off, 시스템 설정 변경하라는 알림창 띄움.
**확인사항**
- 노티피케이션 줄 기간 현재 14일로 지정. 논의 후 변경 가능.
- 저금통 개봉시 노티피케이션 삭제
- 저금통 endDate 자정으로 저장
=> [feat] 로컬 노티피케이션 기능 추가 #91

Happiggy-bank/Happiggy-bank/Assets.xcassets/note-colors/noteListTagWhite.colorset/Contents.json, Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/UIColor+AssetColors.swift, Happiggy-bank/Happiggy-bank/Subview/TagCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/TagViewFlowLayout.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
- 이슈 #101 
<br>
- 태그 셀 색상, 글씨 크기, 굵기, 여백을 반영했습니다
- 첫 단어가 10자를 초과하는 경우 1~10 글자 사이에 랜덤으로 자르게 했습니다 
- 띄어쓰기를 하지 않는 유저의 경우 모든 셀 크기가 같으면 단조로울 것이라고 생각해 이렇게 처리했습니다(저희 목 데이터처럼...)
- 관련해서 기존 왼쪽 정렬 로직에서 버그를 발견해 정렬 로직을 변경했습니다 
- 쪽지 개수가 한 페이지 안에 들어가는 경우 섹션 자체를 가운데 정렬했습니다
=> [feat] 쪽지 태그 리스트 디자인 반영 #101

Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
- 이슈 #109 
<br>
저금통 탭을 누른 후 개봉하게 되면 이미 저금통 탭이 로드된 상태라서 반드시 저금통 리스트에 돌아오면 뷰가 다시 나타나게 되기 때문에 작동하지 않는 문제였습니다...저금통 탭을 누르기 전에는 저금통 리스트 뷰가 로드만 되고 나타나기 전에 쪽지리스트 segue 로 넘어가버려서 해당 애니메이션이 보이지 않았던 것 같은데 사실 이래도 되는건가 싶은 생각이 들긴 합니다...이것저것 해봤는데 스토리보드+현재 구조에서는 마땅한 대안이 없는 거 같아요 나중에 도움 주시면 매우 감사하겠습니다 흑흑 
<br>
일단은 임시방편으로 저금통 리스트 뷰가 이미 로드된 경우에는 리스트 뷰를 모두 숨겨버려서 마치 애니메이션 탭에서 넘어온것처럼 보이게 했습니다!
=> [fix] 저금통 리스트 탭 누른 뒤 개봉하는 경우 쪽지 리스트로 넘어가지 않는 문제 해결 #109

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
- 이슈 #112 
<br>
- 스토리보드는 viewDidLoad 시점에 아직 하위 뷰들이 로드되지 않고, 디바이스 크기가 반영되지 않아 쪽지를 추가하는 영역이 변화하지 않고 있었습니다. 따라서 viewWillLayoutSubviews 로 관련 작업을 이동하고, gravity 가 널인지, 하위뷰들이 로드 되었는지 확인해서 최초에 한 번만 관련 작업을 수행하도록 했습니다...!
<br>
와..! 홈뷰 주요 기능이었는데 지금까지 몰랐다니..! 와 이슈 넘버도 112...! 와...!
=> [fix] 홈뷰에서 디바이스 크기에 따라 bottle note view 크기가 조정되도록 변경 #112

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
issue #63, #81, #123
- 저금통 이름 수정 화면
- 저금통 이름이 없거나 같으면 저장 불가
- 저금통이 없을 때, 있을 때 화면 요소 변경
- 저금통 이름 라벨을 눌렀을 때 저금통 이름 수정 화면으로 이동
=> [feat] 홈 화면 UI 재구성 및 기능 추가 #63, #81, #123

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Happiggy-bank.xcdatamodeld/Happigy-bank.xcdatamodel/contents, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
- 이슈 #114 
<br>
- 저금통 코어데이터 모델에 이미지 어트리뷰트를 추가했습니다. 
- 모델 변경하는 김에 코어데이터 모델에서 저금통 제목 제한을 기존 15자 -> 10자로 변경했습니다 
- 저금통 리스트에서 보여줄 개봉 직전 저금통 상태의 스냅샷을 찍는 메서드를 구현했습니다. 
- 굳이 아래로 쪽지 노드들을 내려보내지 않고 **현재 상태 그대로 캡쳐**되도록 했습니다
- 대신 알림에 현재 모습이 그대로 저장된다는 안내 문구를 넣었습니다
- 용량을 줄이기 위해 컬렉션뷰 셀 크기에 맞춰 리사이징했습니다. 
- 다만 자동으로 소수점이 반올림되는 것 같아서 이 부분은 나중에 셀에 이미지 넣을 때 다시 확인해야할 것 같습니다...! 
- 데이터 관련 내용이라고 생각해서 뷰모델에 해당 메서드를 구현했습니당
- isOpen 을 현재는 홈뷰에서 저장 버튼을 누르는 시점에 처리하도록 했는데 **개봉 처리 시점**에 대해 같이 얘기해보면 좋을 것 같습니다.
=> [feat] 저금통 개봉 시 현재 모습 스냅샷 저장 #114 

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Enum/TabItem.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
- 이슈 #128
<br>
- 항상 메시지 뷰에서 탭하면 쪽지리트스가 페이드인으로 나타나도록 변경했습니다. 
- unwind segue 를 버리고 
1. 탭바 컨트롤러의 인덱스를 저금통 리스트 탭로 이동
2. 스토리보드 뷰컨트롤러 인스턴스화를 통해 저금통 리스트 탭의 네비게이션 뷰 체계를 [저금통 리스트, 쪽지 리스트] 로 변경
3. 메시지 뷰 dismiss
=> 짜잔 쪽지리스트를 드리겠습니다..!
- unwind segue 를 비롯해서 기존 방식과 관련된 메서드들 다 삭제했습니다...!
=> [feat] 저금통 개봉 애니메이션 수정 #128 

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/UIColor+AssetColors.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
- 이슈 #132 
<br>
- 저금통 리스트 셀에 스냅샷을 적용했습니다. 
- 스냅샷 배경이 투명 그대로 유지되도록 저장시 기존 jpeg->png 로 변환했습니다. 
- 중력 작동 전 저금통 뷰에서 쪽지 최대 높이를 조정했습니다. 
- 저금통 개봉 메시지 뷰의 배경들을 다크모드도 지원하도록 변경했습니다. 
- 홈뷰에서 저금통 개봉 시 저금통을 nil 로 바꾸면서 메시지 뷰에 저금통이 전달되지 않아 sender 에 저금통을 넣어서 보내는 방식으로 변경했습니다. 
- 그냥 저금통을 nil 로 바꾸는 순서를 맨 밑으로 내리려다가 나중에 또 헷갈릴 수 있을 것 같아 이렇게 처리했습니당
=> [feat] 저금통 리스트 셀에 스냅샷 적용 #132

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/UITextView+ParagraphStyle.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/View/CustomTabBar.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
- 이슈 #134 
- 이슈 #135 
<br>
- 기존 글자 수 제한 방식 자체에 자잘하게 거슬리는 점들이 있어서 제한 방식을 변경했습니다. 
- 100자가 초과된 상태에서 붙여넣기를 하면 그게 적용된다던가 하는... 
- 텍스트필드도 제가 다 수정했는데(저금통 제목, 저금통 메시지, 저금통 제목 수정 3곳 맞죠...?), 혹시 제가 실수로 삭제한 파트가 있는지 확인 부탁드립니다....! 
- 텍스트뷰에서 기존에는 확인창을 누르면 deleteBackwards 메서드를 이용해서 자르고 있었는데 이게 맨 뒤가 아니라 커서의 위치 기준으로 자른다는 것을 발견했습니다. 그래서 그냥 앞에서부터 100자를 자르도록 변경했습니다. 
- 관련해서 혹시 텍스트필드 글자 자르는 건 어디서 하고 계신가용..?
<br>
- 포그라운드로 돌아올때 노티를 받게 하고, 노티를 받으면 현재 선택된 행의 내용에 맞게 경고 라벨과 틴트컬러 적용 여부를 확인해서 적용하도록 변경했습니다. 
<br>
- 쪽지 디테일 캐러셀의 쪽지 노트 셀 크기를 비율 -> 고정 크기로 변경했습니다. 
- 프로맥스에서 너무 쪽지 여백이 많아져서 아이폰 12 기준으로 고정 크기를 잡아서 아예 모든 디바이스에서 고정 크기로 바꿨습니다. 
- se~프로맥스까지 얼추 괜찮은 것 같은데 베타 돌려봐야...알겠죠...? ㅎ그흑 
- 모션 업데이트 속도를 조정했습니다. 
- 현재 탭바가 커스텀된 상태(높이, 아이템 위치)인데 se에서는 깨지는 현상이 있어 디바이스 높이가 일정 이하면 탭바 커스텀 사항이 적용되지 않도록 했습니다.
=> [feat] 디테일 처리 #134 #135

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/Extensions/UIVIewController+TopMostViewController.swift, Happiggy-bank/Happiggy-bank/Extensions/UIWindowScene+TopMostViewController.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/ErrorViewController.swift
- 이슈 #136
- 앱 처음 실행 시 코어데이터 관련 중대 에러가 발생하는 경우 
- 유저에게 에러가 발생해서 앱을 작동할 수 없고, 팀 메일로 연락달라는 라벨을 띄운 다음, 탭하면 강종되게 처리했습니다. 
- 이를 위해 아예 해당 에러가 발생하면 루트 뷰컨을 에러 뷰컨으로 바꿔줬습니다. 
- 저장 실패 
- 유저에게 변경 사항을 저장하지 못했으며, 저장공간을 확인하고 같은 문제가 반복되면 팀 메일로 연락달라는 라벨을 띄운 다음 탭하면 그냥 알림만 꺼지게 하고 강종되지는 않도록 했습니다.
=> [feat] 코어데이터 에러 알림 처리 #136

Happiggy-bank/Happiggy-bank/Happiggy-bank.xcdatamodeld/Happigy-bank.xcdatamodel/contents, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
- 이슈 #153 
- 이슈 #154 
- 이슈 #155 
- 이슈 #156 
<br>
- 저금통 추가 시 기간 변경 불가, 삭제 불가 알림을 추가했습니다. 
- 새로운 저금통 제목/메시지 작성, 기존 저금통 제목 변경 뷰에서 글자수 제한을 초과하는 경우 초과분을 삭제하도록 처리했습니다. 
- 한영 변환시 글자 수 제한이 작동하지 않는 문제를 해결했습니다. 
- 한글과 기타 언어의 글자수 제한이 달라서 로직에 발생한 문제로 일단은 글자 수 제한을 101자로 통일했고, 추후에 더 나은 해결책을 찾아보겠습니다. 
- 코어데이터 문자열 어트리뷰트들의 글자수 제한을 제거했습니다. 
- 하나의 이모지가 여러 글자로 인식되어 이모지가 포함된 문자열의 경우 실제로 글자 수 제한을 초과하지 않았는데 초과했다고 저장에 실패해 제거했습니다.
=> [feat] 저금통 추가 시 최종 확인 알림, 텍스트 필드 글자수 제한 초과분 삭제, 기타 버그 

Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
저금통이 있고, 쪽지도 있는 경우 홈 뷰의 라벨이 중첩되는 현상을 수정했습니다.
해당 조건에서 라벨 hidden을 하지 않았던 게 문제인 것 같습니다.
이 부분 리팩토링 빠른 시일 내에 꼭 진행하겠습니다!
=> [fix] 홈뷰 라벨 중첩 현상 해결 #160

Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteTextViewModel.swift
##반영내용
- 이슈 #164 
- 이슈 #163 
<br>
- 일단 임시방편으로 코어데이터 에러 발생 시 알림에 문제에 관한 설명을 같이 띄워서 유저가 캡쳐해서 버그 레폿을 보냈을 때 저희가 좀 더 잘 이해할 수 있도록 했습니다...!
- 알림이 나타나자마자 사라졌던 이유는 저장 버튼을 눌렀을 때 에러가 나면 알림을 띄우고 중단되는 게 아니라 선언해뒀던 dismiss/unwind segue 가 이어서 실행되기 때문인 것 같아 에러가 발생하지 않을 때만 dismiss/unwind segue 작업을 수행하도록 분기했습니다. 
<br>
- 101자를 입력받는 것 자체는 100자를 온전히 입력받으려면 어쩔 수 없어서(Swift 한계...8ㅅ8) 대신에 100자를 초과하면 글자 수 라벨에서 현재 글자수 부분이 빨갛게 변하도록 했습니다.
=> [feat][fix] 코어데이터 에러 디버깅 문구 추가, 100자 초과 시 빨간색으로 변경

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Enum/Result.swift, Happiggy-bank/Happiggy-bank/Protocol/Presenter.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/HapticManager.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
- 이슈 #169 
- 이슈 #170 
<br>
- 쪽지들끼리 부딪힐 때 햅틱을 추가하면 정말 진동이 드드드드드드드드득거려서 쪽지가 바운더리와 충돌할 때만 햅틱을 추가했습니다. 
- 저금통 이름 변경 뷰컨트롤러를 띄울 때 중력을 중단했습니다.
- 다른 모달의 경우 다 중력을 아예 중단하거나, 방향을 아래로 고정시키는 등의 작업을 했었는데 저금통 이름 변경 컨트롤러만 호출 방식이 달라서 귀찮아서...그냥 냅뒀었는데요...
- 햅틱을 더 추가하니까 이름 바꾸는 데 계속 진동이 와서 중력을 중단시켰고, 은빈님의 data provider 처럼 프로토콜+델리게이트로 결합도를 낮췄습니다...!
=> [feat] 홈뷰 쪽지들 상호작용 시 햅틱 반응 추가 #169 #170 #171

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Extensions/NSMutableAttributedString+ColorBold.swift, Happiggy-bank/Happiggy-bank/Extensions/NSMutableAttributedString+Hyperlink.swift, Happiggy-bank/Happiggy-bank/Protocol/InformationTextViewDataSource.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/SettingsNonIconButtonCell.xib, Happiggy-bank/Happiggy-bank/Subview/SettingsNonIconButtonCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/LicenseText.swift, Happiggy-bank/Happiggy-bank/ViewController/CustomerServiceViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/InformationTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/CustomerServiceViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/LicenseViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/SettingsViewModel.swift
- 이슈 #144
- 이슈 #173 
<br>
- 버전 2에서 이용약관, 개인보호 처리방침 탭이 생길 예정이므로 환경설정에 고객 지원 탭을 별도로 생성하고 라이선스뷰를 해당 항목의 하위 항목으로 추가했습니다. 
- 최대한 셀 구성 관련 로직을 뷰모델로 빼서 뷰 컨트롤러는 받아서 최종적으로 이를 UI 와 연결하는 역할만 수행하도록 했습니다. 
<br>
- 나중에 이용약관, 개인보호 처리방침 뷰도 같은 형태일거라고 생각해서 재사용성을 높이기 위해 InformationTextViewController 를 생성했습니다. 
- 마찬가지로 결합도를 낮추고 재사용성을 높이기 위해 위해 InformationTextViewDataSource 프로토콜을 선언해서 뷰모델의 타입을 추상화했습니다.
- 각 케이스마다 내비게이션바 제목이랑 텍스트뷰 텍스트만 바뀔거 같아서 이렇게 하면 나중에 재사용하기 쉽겠다..!했는데 나중 가면 또 구려서 엎을수도... 
- 라이선스 내용 중 필요한 곳에 하이퍼링크를 추가했습니다. 
- 하이퍼링크 생성 관련 코드는 익스텐션으로 추가했습니당!
<br>
- (만약 디자이너님이 추가하겠다고 하시면) 아이콘 에셋 반영
=> [feat] 환경설정 탭의 고객지원뷰, 라이선스뷰 구현 #144 #173

Happiggy-bank/Happiggy-bank/Extensions/UIView+FadeInOut.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
- 이슈 #176 
<br>
- 새로운 쪽지 작성 텍스트뷰에 플레이스 홀더를 추가했습니다. 
- "하루 한 번, 100자로 행복을 기록하세요:)"
- 유저가 내용을 작성하면 사라지도록 했고, 내용이 비면 다시 나타나도록 했습니다. 
- UIView 페이드인, 아웃 익스텐션에 가드 문을 추가했습니다. 
- 페이드인의 경우 알파가 0인 경우, 페이드아웃의 경우 알파가 0이 아닌 경우에만 애니메이션 효과가 발동되도록 변경했습니다.
=> [feat] 새로운 쪽지 텍스트뷰에 플레이스홀더 추가 #176

Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
- 이슈 #178 
<br>
- 경고 라벨 페이드 아웃 로직이 현재 화면에 나타나는 행에 사용될 뷰를 리턴하는 델리게이트 메서드에 들어있어서, 스크롤을 적게 하는 경우 이미 필요한 뷰가 모두 그려져 있어 해당 메서드가 호출되지 않기 때문에 발생하는 문제였습니다. 
- 따라서 페이드아웃 로직을 행 선택시 호출되는 델리게이트 메서드로 옮겨줬습니다.
=> [fix] 새로운 쪽지 날짜 피커 경고 라벨 사라지지 않는 현상 해결 #178

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/CustomerServiceViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/CustomerServiceViewModel.swift
- 이슈 #175 
<br>
- 기존에 팀 소개 라벨에 있던 기능을 고객 지원 뷰로 이동했습니다. 
- 메일 앱을 열 수 있는 경우 모달로 메일 작성 메뉴를 띄우고, 불가능한 경우 메일 주소가 써 있는 알림을 띄우도록 했습니다. 
- 팀 라벨에서 메일 주소를 삭제했습니다. 추후에 여기 앱 소개 노션 링크같은 걸 달아도 좋을 것 같아서 일단 탭제스처 레코나이저는 살려뒀습니다...!
=> [feat] 개발자에게 메일 보내기 기능 고객지원 뷰로 이동 #175

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
텍스트가 긴 경우 잘려서 라벨 줄 수 0으로 변경 및 오토레이아웃 재설정
=> [hotfix] 저금통 개봉 애니메이션 뷰 라벨들 잘리는 현상 수정 #195

Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
#193 
- #194 풀리퀘스트에서 bottleData.message 에 텍스트필의 값을 넣어주는데, 비어있는 경우 nil 이 아닌 빈 문자열이 저장되어 디폴트 메시지가 적용되기 위한 else 문으로 들어가지 않아서 발생한 문제
- 조건문에 빈 문자열인지 확인하는 내용을 추가
<br>
#197 
- 위의 상황에서 코어데이터에서 메시지의 최소 길이를 1로 해놔서 빈문자열이 저장되어 코어데이터 에러가 발생. 저장에 실패했더라도 현재 context 자체에는 존재하므로 삭제 처리를 따로 해줘야 해서 추가해줌
=> [hotfix] 저금통 디폴트 메시지 저장 안되는 문제 해결, 코어데이터 실패 시 필요에 따라 해당 엔티티 삭제 처리 #193 #197

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 저금통 개봉 메시지 저장 안되는 문제 해결
- 텍스트필드의 값을 적용하지 않고 있어서 발생했던 문제
- 저금통 이름, 메시지에 이모지가 많이 들어가 저금통 애니메이션 뷰에서 한 줄을 초과하는 경우 텍스트가 잘리는 문제 해결
- 라벨의 줄 수를 모두 0으로 변경하고, 스토리보드에서 오토레이아웃 설정 방식 변경(autoresizing+constraints)
- 코어데이터 오류로 저장에 실패했을 때 필요 시 해당 엔티티 삭제하는 작업 추가
- 새로운 저금통이나 쪽지를 생성하는 경우에 해당하며, 저장에 실패해도 context 자체에는 계속 존재하기 때문에 필요
=> [chore] version 1.0.1 업데이트

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Enum/CustomResult.swift, Happiggy-bank/Happiggy-bank/Enum/OptionalBool.swift, Happiggy-bank/Happiggy-bank/Extensions/NSNotificaion.Name+CustomNotifications.swift, Happiggy-bank/Happiggy-bank/Extensions/UIViewController+VersionUpdating.swift, Happiggy-bank/Happiggy-bank/Extensions/URL+AppStore.swift, Happiggy-bank/Happiggy-bank/Extensions/URL+Open.swift, Happiggy-bank/Happiggy-bank/Model/LookUpResult.swift, Happiggy-bank/Happiggy-bank/Protocol/Presenter.swift, Happiggy-bank/Happiggy-bank/Protocol/VersionChecking.swift, Happiggy-bank/Happiggy-bank/Protocol/VersionUpdating.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/VersionManager.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/SettingsViewModel.swift
- #204 
- #203 
<br>
- 이전에 정의했던 Result Enum 의 이름을 CustomResult 로 변경했습니다. 
- Swift 내장 Result 타입과 중복되어서...멍청한...코드... 
<br>
- 설치 버전과 앱스토어 버전 체크를 위해 VersionChecking 프로토콜을 선언하고 이를 상속하는 VersionMananger 객체를 선언했습니다.
- 업데이트 기능은 VersionUpdating 프로토콜에 선언하고 뷰컨트롤러의 익스텐션이 상속하도록 했습니다. 
- 우린..서버가 없으니까...ㅠ 굉장히 더럽게 앱스토어 엔드포인트에서 받은 릴리즈 노트를 파싱해서 필요 시 강제 업데이트 하도록 로직을 짰습니다... 
- 앱스토어 릴리즈 노트 작성 시 주의가 필요하며 파싱 메서드 위에 // MARK 로 안되는 예시 상세히(...) 달아두었습니다. 
- 파싱 결과 강제 업데이트가 필요한 경우 선택지가 업데이트 뿐인 알림을 띄우도록 했습니다.
- 백그라운드에서 포어그라운드로 돌아올 때마다 강제 업데이트 유무를 확인하도록 했습니다.
- 앱을 시작할 때만 강제 업데이트 유무를 확인하면 백그라운드에서 다시 실행되는 경우가 누락되므로..  
- 인터넷 연결이 안되는 등 업데이트 유무 자체를 확인할 수 없는 경우에는 그냥 앱을 계속 사용하도록 했고, 강제 업데이트가 필요함을 확인했는데 링크 오류 등으로 업데이트를 못하고 있는 경우에는 유저에게 앱을 종료한다고 알리고 종료 버튼을 누르면 앱을 종료하도록 했습니다.
- 인터넷 연결 상황에 따라 정보를 받아오는 작업이 매우 느릴 수 있으므로 URLSession …
=> [feat] 환경설정 앱 버전 정보 셀 로직 추가, 강제 업데이트 기능 추가 #201 #203

Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
- #202 
<br>
- 그리드를 앱을 켰을 때 최초 한 번만 초기화해서 발생했던 문제(실환가...)로 저금통이 추가될 때마다 기간에 맞게 그리드를 다시 생성하도록 변경했습니다...!
=> [fix] 기존 저금통 개봉 후 새로운 저금통 생성 시 기간이 달라도 쪽지 크기가 그대로인 문제 해결 #202

Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/VersionManager.swift
- 앱스토어에서 정보를 받아오는 API 주소를 https -> http 로 변경했습니다!
- http와 https 중 새로운 버전 릴리즈되면 정보 반영이 빠른 게 https 라고 봤는데 http 였나봐요...
=> [fix] 유저가 업데이트를 해도 환경설정 탭 버전 정보에 업데이트가 필요하다고 뜨는 버그 해결 #221

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 유저가 업데이트를 해도 환경설정 탭의 버전 정보에 반영되지 않는 버그 해결
- 앱스토어에서 릴리즈된 버전 정보를 받아오는 엔드포인트 주소를 https -> http 로 변경
=> [chore] 버전 1.0.3 업데이트

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Extensions/Date+Tomorrow.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
- resolves #218 
디바이스 시간을 과거로 돌리는 경우 은빈님이 이전에 제보해주셨던 문제를 비롯해 다음과 같은 사항을 처리했습니다. 
원인은 다 시간여행자를 고려하지 않았다는 것...ㅎ그흑 
- 시간을 과거로 돌리는 경우 돌린 날짜에 이미 쪽지를 작성했어도 다시 쪽지 작성이 가능한 현상
- 기존에는 홈탭에서 화면을 탭하면 과거로 시간을 돌릴 수 있다는 점을 고려하지 않고 항상 가장 최근 날짜에 작성한 쪽지를 가지고 오늘 날짜에 해당하는 지를 확인하는 방식이었는데, 이로 인해 2일에 쪽지를 작성하고 나서 1일로 시간을 돌리면 가장 최근 날짜인 2일의 쪽지를 가지고 1일에 작성했는지 아닌지를 확인하기 때문에 또 다시 작성이 가능해지는 것이었습니다... .
- 따라서 그냥 전체 쪽지 배열을 다 돌면서 디바이스 기준 현재 날짜와 비교해서 해당 날짜의 쪽지가 있는지에 따라 작성 뷰를 띄우는 방식으로 변경했습니다. 
<br>
- 시간을 과거로 돌린 후 백그라운드 -> 포어그라운드로 오는 경우 크래시가 나는 현상
- 마찬가지로 시간을 달릴 수 있다고 생각을 안해서 행 개수는 시작일~오늘까지만큼 날짜 수로 하고, 쪽지는 전체를 다 가져와서 작성 여부를 확인하고 피커에 나타냈는데,  이런 경우 시간을 과거로 돌리면 해당 시점 기준 미래의 쪽지는 존재는 하는데 행에는 나타낼 자리가 없어 인덱스 에러가 발생하면서 크래시가 났습니다. 
- 따라서 쪽지 배열 전체를 돌 때 항상 디바이스의 현재 시점을 기준으로 현재까지의 쪽지만을 나타내도록 했습니다. 
<br>
- 시간을 저금통 생성일 이전으로 돌린 경우 대응 필요
- …
=> [fix] 유저가 디바이스 시간을 과거로 돌리는 경우 발생하는 쪽지 작성 관련 버그 수정 #218

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 목록 탭 쪽지 뷰들 날짜 오름차순으로 변경(과거-최신 순) PR #226
- 유저가 디바이스의 시간을 돌리는 경우 발생하는 쪽지 뷰들 관련 버그들 수정 PR #225
시간을 과거로 돌렸을 때
- 이미 작성한 날짜에 다시 쪽지를 작성할 수 있는 버그 해결
- 날짜 피커 실행 시 크래시 나는 버그 해결
- 저금통 생성일 이전인 경우 새로운 저금통 생성 방지
=> [chore] 버전 1.0.4 업데이트

Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift, Happiggy-bank/Happiggy-bank/Subview/PhotoNoteCell.swift, Happiggy-bank/Happiggy-bank/ViewModel/PhotoNoteCellViewModel.swift
- 쪽지 목록의 note cell, photo note cell에 새로운 색상이 변경되지 않아 반영했습니다. 
- 테두리 선 색상이 연해졌고 
- 몇 번째 쪽지인지 나타내는 레이블 색상이 변경되었습니다.
|전|후|
|---|---|
|<img src="https://user-images.githubusercontent.com/81314063/205196939-054f25ca-774f-4bfb-aef6-614d0c26ca6e.png" width=300>|<img src="https://user-images.githubusercontent.com/81314063/205197249-9a7a2fca-0ed7-4677-ae98-9545b865fc44.jpeg" width=300>|
=> [feat] note cell에 새로운 색상 반영

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Info.plist, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/ViewController/CustomTabBarController.swift
- CustomTabBarController로 진입할 수 있도록 코드 추가
- Main.storyboard key-value 값 삭제
- 기본 색상 설정
- 각 탭의 내비게이션 컨트롤러 생성 **=> 추후 리팩토링 거치면서 각 화면에 맞는 컨트롤러로 변경 필요**
=> [chore] 앱 진입 화면을 Main 스토리보드에서 CustomTabBarController로 수정 #249

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Utils/Network/HTTPMethod.swift, Happiggy-bank/Happiggy-bank/Utils/Network/NetworkError.swift, Happiggy-bank/Happiggy-bank/Utils/Network/NetworkManager.swift, Happiggy-bank/Happiggy-bank/Utils/Network/NetworkServiceable.swift, Happiggy-bank/Happiggy-bank/Utils/Network/Requestable.swift
- resolves #265 
- 네트워크 통신을 위한 네트워크 매니저를 구현했습니다. 
- 버전 매니저 구현 시 통신 관련 기능을 분리하기 위해서 별도의 객체로 나눴습니다. 
- 보내려는 HTTP 리퀘스트를 Requstable 프로토콜을 채택한 타입으로 구현해서 네트워크 매니저의 `func fetchDecodedData<T: Decodable>(for endpoint: Requestable)` 메서드의 인자로 넘기면 데이터를 T 타입으로 디코딩해서 리턴하는 방식입니다!
=> [feat] 네트워크 매니저 구현 #265

Happiggy-bank/Happiggy-bank/Base/UI/Controller/CustomTabBarController.swift
- 최초 앱 사용 시 UserDefaults에 저장된 CustomFont 값이 없어 탭바가 제대로 초기화되지 않는 버그를 수정했습니다.
=> [fix] 탭바 설정 누락되는 문제 해결

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/HomeTab/Home/UI/Controller/HomeTabViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/Controller/NewBottleDateViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/Controller/NewBottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/Controller/NewBottleNameViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/View/NewBottleDateView.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/View/NewBottleMessageView.swift, Happiggy-bank/Happiggy-bank/HomeTab/NewBottle/UI/View/NewBottleNameView.swift, Happiggy-bank/Happiggy-bank/Utils/Extensions/CATransition+PopupAnimation.swift, Happiggy-bank/Happiggy-bank/Utils/Extensions/UINavigationController+transition.swift, Happiggy-bank/Happiggy-bank/Utils/Extensions/UIViewController/UIViewController+FadeInOut.swift, Happiggy-bank/Happiggy-bank/Utils/Protocol/DataProvider.swift
resolves #284 
- navigationController 관련 코드 수정
- fade in/out 적용된 push, pop 메서드 extension으로 생성
- NewBottleName
- UI 코드로 생성
- Controller 생성(원래 NewBottleNameFieldViewController)
- NewBottleDate
- UI 코드로 생성
- Controller 생성(원래 NewBottleDatePickerViewController)
- Ver2에서 완전 바뀔 예정이라서 리팩토링 따로 안 함. viewModel도 원래 있던 컨트롤러에서 생성한 것 그대로 썼습니다.
- NewBottleMessage
- UI 코드로 생성
- Controller 생성(원래 NewBottleMessageFieldViewController)
- fetchedResultsController는 한번에 작업할 예정입니다. 여기 관련 코드 없어요!
- 그래서 NewBottleMessageController에 `save`하는 부분이 리팩토링이 덜 됐습니닷.
=> **그 바이러스때문에 많이 힘드시겠지만 UI 관련 코드이니만큼 금방 확인 해 주시면 코어데이터 관련 작업을 바로 들어갈 수 있을 것 같아용**(물론 브랜치 따서 해도 됩니다 그저 컨플릭트가 아주많이 날 것 같아서 두려울 뿐...이므로 아 몰라 배째 하셔도 됨 ㅎ)
=> [feat] 새 저금통 생성 화면, 컨트롤러 코드 생성

Happiggy-bank/Happiggy-bank/Base/Model/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Base/Model/Note+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Base/UI/Controller/CustomNavigationController.swift, Happiggy-bank/Happiggy-bank/Base/UI/Controller/CustomTabBarController.swift, Happiggy-bank/Happiggy-bank/Base/UI/View/CustomTabBar.swift, Happiggy-bank/Happiggy-bank/HomeTab/Home/UI/Controller/HomeTabViewController.swift, Happiggy-bank/Happiggy-bank/ListTab/BotteList/UI/Controller/ListTabViewController.swift
- resolves #286
- resolves #287 
- resolves #288 
<br>
해당 PR의 내용을 간단히 한 줄로 작성해주세요.
- 탭바 컨트롤러, 네비게이션바 컨트롤러 UI 디자인을 반영했습니다. 
- 저금통 및 쪽지 목데이터를 추가했습니다. 
- swift 파일 명, 클래스/메서드 이름 등 작업한 상세 내용 간략히 서술해주세요.
**저금통 목데이터**
- `fooOpenBottles`: 모든 기간의 개봉 저금통이 1개씩 담긴 저금통 배열 리턴
-  `fooOpened(duration:openedNdaysBefore)`: 원하는 기간의 N일 전에 개봉된 저금통 리턴
-  `fooInProgress(duration:daysLeft:)`: 원하는 기간의 개봉까지 N일 남은 진행중인 저금통 리턴
<br>
=> [feat] 탭바 컨트롤러, 네비게이션 컨트롤러 디자인 반영 및 목데이터 추가  #286 #287 #288 

Happiggy-bank/Happiggy-bank/HomeTab/Home/ViewModel/HomeTabViewModel.swift
- resolves #296 
D-Day가 지난 날부터 숫자 앞에 - 라벨이 붙는 현상 수정
- HomeTabViewModel 변경
X
=> [fix] D-day 라벨에 +,-가 중복으로 뜨는 현상 수정 #296

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/HomeTab/Home/UI/Controller/HomeBottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/Home/UI/Controller/HomeTabViewController.swift, Happiggy-bank/Happiggy-bank/HomeTab/Home/UI/View/BottleNameEditView.swift, Happiggy-bank/Happiggy-bank/Utils/Protocol/DataProvider.swift
- resolves #304 
HomeView의 오른쪽 위 버튼에서 접근할 수 있는 BottleNameEditViewController(저금통 이름 변경하는 뷰 컨트롤러) 리팩토링
- BottleNameEditView
- HomeBottleNameEditViewController -> 기존에 BottleNameEditViewController를 일단 살려놓기 위해 Home을 붙였습니다.
- HomeTabViewController
- DataProvider
X
=> [refactor] BottleNameEditViewController 리팩토링 #304

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/SettingsTab/Notification/UI/Controller/NotificationSettingViewController.swift, Happiggy-bank/Happiggy-bank/SettingsTab/Notification/UI/View/NotificationSettingTableViewCell.swift, Happiggy-bank/Happiggy-bank/SettingsTab/Notification/ViewModel/NotificationSettingViewModel.swift, Happiggy-bank/Happiggy-bank/SettingsTab/Tab/UI/Controller/SettingsViewController.swift
- resolves #306 
로컬 노티피케이션 관련 코드 리팩토링 진행.
로컬 노티가 늘거나 혹은 푸시 노티를 추가해야할 때 이에 대한 설정 정보(알림 on/off, 시간 등)를 따로 DB에 저장해야하나 생각했는데 데이터 저장소 관련해서 아티클 몇 개 읽고 생각해봤을 때 그냥 UserDefaults 쓰는 것이 가장 합리적인 것 같아서 일단 이대로 진행했습니다.
- NotificationSettingsViewController의 내용을 변경했습니다.
- 중복되는 코드를 줄였습니다.
- NotificationSettingsViewModel의 내용을 변경했습니다.
- 알림이 더 늘어나도 Content에 추가하면 됩니다. (단, 타임피커 관련 코드는 일부 수정해야 함)
- NotificationToggleCell의 내용을 변경했습니다.
- NotificationSettingViewController 객체 생성하는 부분을 추가했습니다.
=> [refactor] 로컬 노티피케이션 관련 코드 리팩토링 #306
