Happynyamy/Happiggy-bank-iOS

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Enum/DateFormat.swift, Happiggy-bank/Happiggy-bank/Extensions/Date+Formatted.swift, Happiggy-bank/Happiggy-bank/Extensions/String+BoldAttributedString.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib, Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
- 이슈 #35 
<br>
- 전체적으로 위치 이동
<br>
- 테이블뷰 사용, cell 은 xib 파일로 생성
- 애니메이션은 일단 임시방편으로 기본 애니메이션 넣어놓음 **월요일 회의 떄 논의 필요**
- 코어데이터 저장 구현(현재는 코멘트 처리)
- 첫 개봉 이후에는 선택해도 변경 없도록 처리
- 지금은 개발 편의를 위해 토글되도록 해놓음
- 내비게이션 타이틀로 저금통 제목 설정
<br>
- 부분적으로 볼드 효과를 준 문자열 생성 위해 익스텐션 추가 
<br>
- fetch request 메서드에서 isOpen_ 으로 조건 오타 난 부분 isOpen 으로 변경
<br>
- 뒤로가기 버튼 제목 빈 문자열로 설정
<br>
- 전체 개봉 버튼 위치 결정되면 관련 뷰 및 로직 추가 예정
- 애니메이션
=> [feat] 쪽지 리스트 구현 #35

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Subview/NoteView.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/Utils/Gravity.swift, Happiggy-bank/Happiggy-bank/View/BottleNoteView.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
#63 
- HomeView에 Bottle 프레임 관련 이미지 추가
- BottleView에 애니메이션 들어갈 뷰 추가
- 라벨 추가 (추후 터치 동작, 타이틀 표시 추가해야 함)
- HomeViewModel 추가 (추후 타이틀 표시 관련 데이터 처리 로직 추가해야 함)
- 애니메이션 로직 기본으로 구현 (추후 @skkimeo 수정)
- 애니메이션에 사용할 쪽지 노드
- imageView로 쪽지 표현
- path 관련해서 추후 수정
- Constants 수정
=> [feat] 홈 화면, 저금통 화면 뷰 구성 #63

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib, Happiggy-bank/Happiggy-bank/Storyboard/NewNoteDatePickerRowView.xib, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift
issue #8
- Storyboard 수정 및 불필요한 코드 삭제
- 라벨 위치 수정
- Storyboard 수정 및 불필요한 코드 삭제
- 피커의 각 행 UILabel로 지정 및 선택시 색깔 변경
- Error: "Unbalanced calls to begin/end appearance transitions"
- NewBottleDatePicker -> BottleView로 unwind시 에러 발생.
- unwind시 NewBottleNameField가 appear됐다가 disappear되는데 이게 BottleView의 appear와 충돌하는 것 같음.
- 관련해서 더 해결해야 합니다. 같은 문제 발생했거나 해결방법 찾으면 코멘트 달아주세요!
=> [feat] 저금통 추가 화면 UI 재구성 #8

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
- 이슈 #48 
- 멘토링 전 코어데이터 작동 확인을 위해 전체적으로 관련 코드를 수정했고, 작동하는 거 확인하고 지금은 주석 처리해서 풀리퀘 날렸습니다...!
- 기간별 완료 저금통 목 데이터를 추가했습니다.
=> [feat] 코어데이터 작동 확인, 목 데이터 추가 #48

Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift, Happiggy-bank/Happiggy-bank/Happiggy-bank.xcdatamodeld/Happigy-bank.xcdatamodel/contents, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
- 이슈 #87 
<br>
- 저금통 -> 쪽지 관계 외에 모든 어트리뷰트 논옵셔널로 변경했습니다
- 저금통에 message 어트리뷰트를 추가했습니다
- 최소 1자 ~ 최대 15자 제한 추가
- 클래스 익스텐션에 닐 코알리싱 프로퍼티 추가
- 클래스 익스텐션의 init 에도 메시지 인자 추가
- 쪽지의 isOpen 어트리뷰트를 삭제했습니다
=> [feat] 데이터 모델 수정 #87

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
Reverts Happiggy/Happiggy-bank-iOS#100
=> Revert "[feat] 개발자에게 메일 보내기 구현 #95"

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib, Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
issue #120 
- 기존 tableView 관련 코드들 collectionView로 변경
- tableView에 정의된 동일한 기능의 함수 collectionView의 함수로 변경
- xib파일과 swift파일
- 필요 없는 코드 삭제
- 영역 확인하라고 imageView에 임시로 이미지 넣어뒀습니다. 빼고 작업하시면 됩니다.
=> [feat] 저금통 리스트 UI 변경 #120

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarHomeNormal.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarHomeSelected.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarListNormal.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarListSelected.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsNormal.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsSelected.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/colors/customGray.colorset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/colors/customLightGray.colorset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/colors/tabBarBackground.colorset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/colors/tabBarDivider.colorset/Contents.json, Happiggy-bank/Happiggy-bank/Button/ColorButton.swift, Happiggy-bank/Happiggy-bank/Extensions/UIColor+AssetColors.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/NewNoteDatePickerRowView.xib, Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib, Happiggy-bank/Happiggy-bank/Storyboard/SettingsLabelButtonCell.xib, Happiggy-bank/Happiggy-bank/Storyboard/SettingsToggleButtonCell.xib, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/View/CustomTabBar.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NewNoteTextViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NoteDetailViewModel.swift
- 이슈 #116 
<br>
- 버튼을 전체적으로 교체했습니다 
- 활성화 비활성화 무관하게 한 가지 색상만 쓰도록 처리했고, 에셋에 틴트컬러가 적용되지 않고 그대로 쓰이도록 render mode 를 original 로 설정했습니다 
- 탭바에 디자인을 적용했습니다. 
- 선택/미선택 시 아이콘을 적용했습니다. 
- 탭바 크기와 탭 아이템 위치 조정을 위해 커스텀탭바 클래스를 생성했습니다. 
- Accent 컬러를 초록색으로 설정했습니다.    
- 전체적으로 폰트 크기와 색상을 다시 확인했습니다.
<br>
- 앱을 이미 킨 상태에서 다크<->라이트로 전환하는 경우 기본 백 버튼이 변경되지 않는 문제가 있습니다...찾아보니 uikit 자체 버그래서 일단...뒀습니다...ㅎ
- 환경설정 뷰 UI 적용
=> Feat/update UI

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Assets.xcassets/characters/homeCharacterInitial.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/characters/homeCharacterInitial.imageset/homeCharacterInitialDarkmode.svg, Happiggy-bank/Happiggy-bank/Assets.xcassets/characters/homeCharacterInitial.imageset/homeCharacterInitialLightmode.svg, Happiggy-bank/Happiggy-bank/Protocol/UpdateSender.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
issue #130 
- HomeViewController
- 조건에 따라 뷰 변화
- 코어데이터와 연동
- 이미지 오토레이아웃
- date picker 강조색 적용
=> Rebased data binding

Happiggy-bank/Happiggy-bank/AppDelegate.swift
=> [feat] 세로모드 고정 #84

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/LaunchScreen.storyboard
=> [feat] 런치스크린 추가 #122

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Assets.xcassets/colors/settingsIcon.colorset/Contents.json, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Storyboard/SettingsLabelButtonCell.xib, Happiggy-bank/Happiggy-bank/Storyboard/SettingsToggleButtonCell.xib, Happiggy-bank/Happiggy-bank/Subview/SettingsLabelButtonCell.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/SettingsViewModel.swift
##반영 내용
- 이슈 #144 
- 이슈 #142 
<br>
- UI 디자인 변화를 반영해 셀 간 간격을 조정하고, 아이콘 색상을 적용했습니다. 
- 버전 정보 셀 UI 를 구성했습니다. 
- 일단 단순 라벨로 뒀고 추후에 앱스토어에 올린 후에 작업할 예정입니다
- **라이선스 셀 UI를 구성**했습니다. 
- 버전 정보 셀 하는김에 낼 하게 될 사람 조금이라도 편하라고 같이 해버렸고, 아이콘은 은빈님 취향대로 넣으셔도 되고 아님 디자이너님한테 내일 물어보려고 합니다...제가 대충 보긴 했는데 잘 모르겠어서.. 
- 파일 하단에 델리게이트 메서드에서 didSelect 하는 부분까지 작성해두었고, TODO로 라이선스 뷰컨으로 넘어가는 것부터 구현하면 된다고 마크해두었습니다...!
<br>
- 버전 정보 셀 로직 추가
=> [feat] 환경설정 셀 업데이트 #142 #144

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
드 디 어 베 타 테 스 트 ! 고생하셨어요 진짜 베타 하는 날이 오긴하네요...흑흑
- 번들아이디를 변경했습니다.
- 앱스토어 정책이 특수문자는 안돼서 제거했습니다
- 앱 업로드를 위해 프로비저닝 파일을 추가했습니다.
=> [chore] test flight 1.0.0 준비

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 베타기간 동안 빌드명 0.x.x
- 앱 이름 Happiggy-bank -> 행복저금통으로 변경
=> [chore] 앱 이름 변경, 버전 0.0.0 #159

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Extensions/UINavigationBar+Clear.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/InformationTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
- 내비게이션 바 투명화 코드 익스텐션 생성 및 해당 부분 기존 코드 모두 새로운 익스텐션 메서드로 대체
- 해당 작업이 여러 곳에서 반복돼서 아예 익스텐션으로 빼주었습니다...!
=> [refactor] 내비게이션 바 투명화 익스텐션 생성

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
issue #168 #181 
- 라벨 업데이트 관련 메서드 실행
- 저금통 개봉 시점에서 스케줄링된 모든 노티피케이션 제거
=> [fix] 노티피케이션 알림 반복 현상 수정 및 D-day 업데이트 정상화 #168, #181

Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/ErrorViewController.swift
##반영 내용
- 이슈 #163 
이전에 저장 오류에는 알림에 디버깅 문구를 추가헸는데, 오늘 생각해보니 앱 로딩 시 초기에 발생할 수 있는 코어데이터 오류에는 해당 처리를 해주지 않아 추가했습니다...!
=> [feat] 에러 뷰 컨트롤러에 코어 데이터 에러 디버깅용 문구 추가 #163

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewModel/CustomerServiceViewModel.swift
각각 행복냠냠이, happynyamy@gmail.com 으로 교체
=> [feat] 팀 이름, 팀 메일 주소 변경

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 버전 1.0.0, 빌드 04.25.1.0.0(날짜-버전) 으로 변경
- 배포를 위해 프로비저닝 파일 등록
- 해당 버전으로 아카이빙해서 업로드
=> [chore] 버전 1.0.0 출시 준비

README.md
=> [docs] 버전 1.0.0 리드미 업데이트

Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift
- 새로운 저금통 개봉 메시지 누락 문제 해결 #193
=> [hotfix] 새로운 저금통 개봉 메시지 누락 문제 해결 #193

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
- 이슈 #209 
- 상향 사유는 이슈에 다 적어두었습니당
=> [chore] iOS 최소 지원 버전 14로 상향 #209

Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift
- closes #217 
- 쪽지 리스트를 날짜순으로 바꾸는 게 더 자연스럽다는 의견에 따라 과거 -> 최신 순으로 보이도록 변경했습니다.
=> [feat] 쪽지 리스트에서 오래된 쪽지부터 보이도록 변경 #217

Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/moreButton.imageset/Contents.json, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/moreButton.imageset/btn_menu-2.svg, Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/moreButton.imageset/btn_menu.svg, Happiggy-bank/Happiggy-bank/Extensions/UIAlertController+BasicFormat.swift, Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/Utils/Constants.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
- 해당 기능 작업 브랜치와 디벨롭이 모두 stale 브랜치가 되었길래 기존 PR(#224)를 머지 없이 닫고 디벨롭으로 날리는 새로운 PR를 열었습니다. 코드 상 변경사항은 없습니다!
<br>
- 중도 개봉에 따른 **알림 초기화 부분 추가 부탁드립니당**!
=> [feat] 홈 탭에 더보기 버튼 및 중도 개봉 기능 추가

Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard, Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
- 강제 종료 현상 해결 
<br>
코드에 코멘트로 달았습니다!
=> [fix] Xcode 14, iOS 16에서 쪽지 작성창에서 취소/저장 버튼 탭 시 강제 종료되는 현상 해결 #237

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [chore] SnapKit SPM 설치 #250

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank.xcodeproj/xcshareddata/xcschemes/Happiggy-bank.xcscheme, Happiggy-bank/Happiggy-bank/Extensions/UIView+FadeInOut.swift, Happiggy-bank/Happiggy-bank/Utils/DebugPrint.swift
- #253 
- #254 
- 디버깅 시에만 나타나도록 print문을 별도로 선언했습니다. 
- fade in/out 을 isHidden을 사용하도록 변경했습니다. 
<br>
https://user-images.githubusercontent.com/81314063/208866857-6f8103b3-7a31-4046-8f2f-414746a88b9b.mp4
=> [refactor] fade in/out isHidden을 사용하도록 변경 

Happiggy-bank/Happiggy-bank.xcodeproj/xcshareddata/xcschemes/Happiggy-bank.xcscheme, Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift, Happiggy-bank/Happiggy-bank/SceneDelegate.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift, Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift, Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift, Happiggy-bank/Happiggy-bank/ViewModel/NotificationSettingsViewModel.swift
- resolves #259 
- CoreData CRUD 메서드들의 리턴 타입을 Result 타입으로 변경했습니다. 
- 메서드 네이밍이 겹쳐서 빌드가 안돼서 기존 메서드들에 old를 붙여주었습니다...ㅎ
=> [refactor] CoreData CRUD 메서드들 리턴 타입 변경 #259

Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj, Happiggy-bank/Happiggy-bank/Subview/BaseButton.swift, Happiggy-bank/Happiggy-bank/Subview/BaseLabel.swift, Happiggy-bank/Happiggy-bank/Subview/BaseTextField.swift, Happiggy-bank/Happiggy-bank/Subview/BaseTextView.swift
- 커스텀 폰트 적용을 위해 BaseLabel, BaseTextView, BaseTextField, BaseButton 클래스를 선언했습니다. 
- 세부 내용은 나중에 해당 파트 리팩토링할 때 할게용! 잊고 있다가 빨리 PR 날려야겠다 싶어서 껍데기만 올립니다. 
- 작업하면서 이번에 미처 생성하지 못한 Base class가 필요한 경우 바로 생성해서 사용하고 서로 말만 해주면 될 것 같아요! 
- 일단은 final 클래스로 명시해놨는데 상속이 필요한 경우 제거하고 사용하면 될 것 같습니다!
=> [refactor] 커스텀 폰트 적용을 위한 베이스 클래스 생성 #263
